language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  app: mighty-sierra-74080
  on:
    repo: yaminmhd/github-react-finder
  api_key:
    secure: H23WW8JkDPBUSS/zEojot8nt/mQFYhrhEkaLcL+VtdHQo3yLnf0zhLLOSH1GEa9ZoELilTvi267lkxyMUC2Yw4LNKfs3ucWzwpgo5hJHFZ9UE+KgaGmNM5bCsqG7VEI9njdRFppbwKekAW+OuWyru4seh2v9aA+nHGAyh5FDN4uTZk5d8hctd2MabbBVIyRXFAwP3ky0Y/4qIlcSYoJ0/8txGv3bAnAeiEEc30iu8uPNPsLCo0ko94Wn9geMRBMc5Vh195EXBUJsCjXp7k9aSdCsbftZTMQruP9jLh7LsSeaoylhGV7pj6bW63kWs5dO0hTypBqixjgWucTPgmSALMuoiBoK9gzSxUwJvQxATDFBVUEAabLcY0Z+cHiP6BuFuCTA34YLEB5iYpgISVtW0+22oMKKTo0otBPHUs5eXgSac6kdv8X77PZ8L0J7VSe0g02XnCx0nnCGtsHTDH/8O5NohNQCdaXPFh6z9RhJmtnp+R12gjTfN1Vin2baUpZfehGTw1Kvl29KQJ9SMnowYkos/j1j0wwmgN0zfDN0qjIYFX1cwhHEm0F1m9jDG5eHb0/fqHjLFLYHBmquvUwZhpt0EG3ALTpmzo6yvJ8Fk2LIRFuUYlLrLvXYKM1r5nyXIyxEu1hUR7Ex2vitvKpFkJZhn5pyy1rUK6gFIQiJeDY=
